---
# handlers file for beats

- name: restart the service
  systemd: 
    name: "{{ beat_product }}" 
    state: restarted 
    enabled: true
  when: start_service and restart_on_change #and not beats_started.changed
