---

- name: Gracefully stop and remove kibana package if switching between OSS and standard
  become: yes
  block:
  - name: Check if the kibana package is installed
    shell: "dpkg-query -W -f'${Status}' {{ kibana_other_package_name }}"
    register: kibana_package
    failed_when: False
    changed_when: False
    check_mode: no
  
  - when: kibana_package.stdout == 'install ok installed'
    block:
    # - name: unhold kibana package when switching to a different package type
    #   become: yes
    #   dpkg_selections:
    #     name: "{{ kibana_other_package_name }}"
    #     selection: "install"

    - name: stop kibana
      service:
        name: 'kibana'
        state: stopped

    - name: Debian - Remove kibana package if we are switching to a different package type
      apt:
        name: '{{ kibana_other_package_name }}'
        state: absent


- name: HTTPS APT transport
  apt:
    name: apt-transport-https
    state: present

- name: Add kibana apt key
  apt_key:
    url: "{{ kibana_apt_key }}"
    state: present

- name: Add Kibana repository
  apt_repository:
    # repo: 'deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main'
    repo: "{{ kibana_apt_url }}"
    state: present
    update_cache: true

- name: Install Kibana
  apt:
    name: '{{ kibana_package_name }}{% if kibana_version is defined and kibana_version != "" %}={{ kibana_version }}{% endif %}'
    state: present
